package base

const (
	CALL_DIRECTION_INBOUND = iota
	CALL_DIRECTION_OUTBOUND
)

const (
	CALL_CAUSE_NONE                           = 0
	CALL_CAUSE_UNALLOCATED_NUMBER             = 1
	CALL_CAUSE_NO_ROUTE_TRANSIT_NET           = 2
	CALL_CAUSE_NO_ROUTE_DESTINATION           = 3
	CALL_CAUSE_CHANNEL_UNACCEPTABLE           = 6
	CALL_CAUSE_CALL_AWARDED_DELIVERED         = 7
	CALL_CAUSE_NORMAL_CLEARING                = 16
	CALL_CAUSE_USER_BUSY                      = 17
	CALL_CAUSE_NO_USER_RESPONSE               = 18
	CALL_CAUSE_NO_ANSWER                      = 19
	CALL_CAUSE_SUBSCRIBER_ABSENT              = 20
	CALL_CAUSE_CALL_REJECTED                  = 21
	CALL_CAUSE_NUMBER_CHANGED                 = 22
	CALL_CAUSE_REDIRECTION_TO_NEW_DESTINATION = 23
	CALL_CAUSE_EXCHANGE_ROUTING_ERROR         = 25
	CALL_CAUSE_DESTINATION_OUT_OF_ORDER       = 27
	CALL_CAUSE_INVALID_NUMBER_FORMAT          = 28
	CALL_CAUSE_FACILITY_REJECTED              = 29
	CALL_CAUSE_RESPONSE_TO_STATUS_ENQUIRY     = 30
	CALL_CAUSE_NORMAL_UNSPECIFIED             = 31
	CALL_CAUSE_NORMAL_CIRCUIT_CONGESTION      = 34
	CALL_CAUSE_NETWORK_OUT_OF_ORDER           = 38
	CALL_CAUSE_NORMAL_TEMPORARY_FAILURE       = 41
	CALL_CAUSE_CALL_CONGESTION                = 42
	CALL_CAUSE_ACCESS_INFO_DISCARDED          = 43
	CALL_CAUSE_REQUESTED_CHAN_UNAVAIL         = 44
	CALL_CAUSE_PRE_EMPTED                     = 45
	CALL_CAUSE_FACILITY_NOT_SUBSCRIBED        = 50
	CALL_CAUSE_OUTGOING_CALL_BARRED           = 52
	CALL_CAUSE_INCOMING_CALL_BARRED           = 54
	CALL_CAUSE_BEARERCAPABILITY_NOTAUTH       = 57
	CALL_CAUSE_BEARERCAPABILITY_NOTAVAIL      = 58
	CALL_CAUSE_SERVICE_UNAVAILABLE            = 63
	CALL_CAUSE_BEARERCAPABILITY_NOTIMPL       = 65
	CALL_CAUSE_CHAN_NOT_IMPLEMENTED           = 66
	CALL_CAUSE_FACILITY_NOT_IMPLEMENTED       = 69
	CALL_CAUSE_SERVICE_NOT_IMPLEMENTED        = 79
	CALL_CAUSE_INVALID_CALL_REFERENCE         = 81
	CALL_CAUSE_INCOMPATIBLE_DESTINATION       = 88
	CALL_CAUSE_INVALID_MSG_UNSPECIFIED        = 95
	CALL_CAUSE_MANDATORY_IE_MISSING           = 96
	CALL_CAUSE_MESSAGE_TYPE_NONEXIST          = 97
	CALL_CAUSE_WRONG_MESSAGE                  = 98
	CALL_CAUSE_IE_NONEXIST                    = 99
	CALL_CAUSE_INVALID_IE_CONTENTS            = 100
	CALL_CAUSE_WRONG_CALL_STATE               = 101
	CALL_CAUSE_RECOVERY_ON_TIMER_EXPIRE       = 102
	CALL_CAUSE_MANDATORY_IE_LENGTH_ERROR      = 103
	CALL_CAUSE_PROTOCOL_ERROR                 = 111
	CALL_CAUSE_INTERWORKING                   = 127
	CALL_CAUSE_SUCCESS                        = 142
	CALL_CAUSE_ORIGINATOR_CANCEL              = 487
	CALL_CAUSE_CRASH                          = 500
	CALL_CAUSE_SYSTEM_SHUTDOWN                = 501
	CALL_CAUSE_LOSE_RACE                      = 502
	CALL_CAUSE_MANAGER_REQUEST                = 503
	CALL_CAUSE_BLIND_TRANSFER                 = 600
	CALL_CAUSE_ATTENDED_TRANSFER              = 601
	CALL_CAUSE_ALLOTTED_TIMEOUT               = 602
	CALL_CAUSE_USER_CHALLENGE                 = 603
	CALL_CAUSE_MEDIA_TIMEOUT                  = 604
	CALL_CAUSE_PICKED_OFF                     = 605
	CALL_CAUSE_USER_NOT_REGISTERED            = 606
	CALL_CAUSE_PROGRESS_TIMEOUT               = 607
	CALL_CAUSE_INVALID_GATEWAY                = 608
	CALL_CAUSE_GATEWAY_DOWN                   = 609
	CALL_CAUSE_INVALID_URL                    = 610
	CALL_CAUSE_INVALID_PROFILE                = 611
	CALL_CAUSE_NO_PICKUP                      = 612
	CALL_CAUSE_SRTP_READ_ERROR                = 613
)

type Call struct {
	Direction int `json:"direction"`
	Cause     int `json:"cause"`
}
